## MODULE:
1. pre-defined modules
2. User-defined modules

## Pre defined modules

In [2]:
import string
string.digits

'0123456789'

In [3]:
import string as s
s.digits

'0123456789'

In [4]:
from string import digits,punctuation
print(digits)
print(punctuation)


0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [1]:
from string import *
print(digits)
print(punctuation)



0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


## User-defined modules

In [4]:
import operations as o
o.wish('justin')

Good afternoon  justin


In [5]:
o.result

'True'

## BUILT-IN LIBRARIES:
1. math


In [7]:
import math
math.factorial(5)

120

In [12]:
#using math module find out Area of the circle
def area(radius):
    
    return math.pi * math.pow(radius,2) 
area(7)


153.93804002589985

In [17]:
import statistics as st
l1 = list(range(1,21))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [18]:
print(st.mean(l1))
print(sum(l1)/len(l1))

10.5
10.5


In [20]:
print(st.median(l1))

10.5


In [23]:
l2 = [1,2,3,4,3,3,4,2,2,2]
print(st.mode(l2))

2


In [24]:
st.stdev(l2)

0.9660917830792959

In [25]:
st.variance(l2)

0.9333333333333333

## random:
1. randint() -->randint(start,stop)start and stop are included
2. randrange() -->stop value is excluded
3. random() --> 0-1
4. choice() --> gives u a single element
5. choices()-->gives u multiple elements

In [27]:
import random
print(random.randint(1,10))
print(random.randrange(1,10))
print(random.random())

9
3
0.3607817274260523


In [32]:
l1=[1,2,3,4,5,6,7,8]
print(random.choice(l1))
print(random.choices(l1,k=3))


3
[4, 1, 1]


## os:

1. rename() --> Renaming
2. remove() --> removing
3. mkdir() -->make a directory
4. getcwd() --> get current working directory
5. listdir() --> gives you list of things
6. chdir() --> change directory
7. rmdir() --> removing the directory

In [34]:
import os
os.mkdir('sample')

In [35]:
os.getcwd()

'C:\\Users\\hp\\Desktop\\internship\\day 9'

In [36]:
os.listdir()

['.ipynb_checkpoints',
 '03-06-2020.ipynb',
 'operations.py',
 'sample',
 '__pycache__']

In [ ]:
os.getcwd('wanted directory link')

In [37]:
os.rmdir('sample')

## numpy package:
1. operations releted numrics
2. computational operation

In [39]:
import numpy as np
l1 = [1,2,3,4,5]
arr1= np.array(l1)
arr1

array([1, 2, 3, 4, 5])

In [40]:
type(arr1)

numpy.ndarray

In [41]:
l2 = list(range(1,11))
l2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [44]:
arr2= np.arange(1,11)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 ### differences between python list and numpy array
 1. less memory
 2. fast
 3. convenient

In [49]:
# array occupis less memory than list
import sys
size = 1000
l1 = list(range(size))
print(sys.getsizeof(l1[0])*size)
arr1 = np.arange(1000)
print(arr1.itemsize * arr1.size)

24000
4000


In [53]:
# Numpy arrys are faster
import time
size = 2000
l1 = list(range(size))
l2 = list(range(size))
start = time.time()
result =[x+y for x,y in zip(l1,l2)]
print("time took for python list: ",time.time()-start)

arr1 =np.arange(size)
arr2 =np.arange(size)
start = time.time()
result = arr1 + arr2
print("time took for python array: ",time.time()-start)

time took for python list:  0.0010020732879638672
time took for python array:  0.0010001659393310547


In [54]:
l1 = [1,2,3,4,5]
l2 = [10,11,12,13,14]
result =[x+y for x,y in zip(l1,l2)]


In [55]:

result

[11, 13, 15, 17, 19]

In [57]:
# numpy arrays are convenient
arr1 =np.array(l1)
arr2 =np.array(l2)
result = arr1 + arr2

In [58]:
result

array([11, 13, 15, 17, 19])