## numpy

In [3]:
#1-dimensional array
import numpy as np
a = np.array([1,2,3,4,5])
print(a.ndim)

1


In [7]:
#2-dimensional array
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a1.shape

(3, 3)

In [10]:
a1.ndim

2

In [12]:
a3 = np.array([],dtype='int32')


In [13]:
a3 =np.append(a3,int(input()))
a3

12


array([12])

In [14]:
a3 =np.append(a3,[23,34,45,56,67])

In [16]:
a3

array([12, 23, 34, 45, 56, 67])

In [20]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [21]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
a3

array([12, 23, 34, 45, 56, 67])

In [24]:
a3

array([12, 23, 34, 45, 56, 67])

## Slicing

In [25]:
a3[3]

45

In [26]:
a2[1,1]

5

In [27]:
a2[2:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [28]:
a2[2:,0:2]

array([[ 7,  8],
       [10, 11]])

In [29]:
a2[0,0:2]

array([1, 2])

In [30]:
a2[0::2,:] #printing alternate rows

array([[1, 2, 3],
       [7, 8, 9]])

 ## iterate throuh array:

In [31]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [34]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [36]:
np.array(a2.flat) #converts to 1-d array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Indexing with boolean array

In [41]:
arr1 = np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
r = (arr1 % 2 == 0)

In [44]:
r

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [45]:
arr1[r]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## appending array

In [48]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)


In [49]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 

In [50]:
arr2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [54]:
print(np.vstack((arr1,arr2))) #vertical stacking

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [56]:
print(np.hstack((arr1,arr2))) #horizontal stacking

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [59]:
arr =np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
4
int32
2
(2, 5)


# functions:
1. zeros()
2. ones()
3. full()
4. eye()
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [62]:
z = np.zeros((2,3),dtype='int32')
z

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
z = np.ones((2,3),dtype='int32')
z

array([[1, 1, 1],
       [1, 1, 1]])

In [67]:
f = np.full((2,2),'raj')
print(f)

[['raj' 'raj']
 ['raj' 'raj']]


In [68]:
#eye()
e=np.eye(3,dtype='int32')
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
#linespace() --> linear spacing elements
l = np.linspace(1,10,5)
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [77]:
a=np.arange(1,13,2) #arange(start,stop,step)
a

array([ 1,  3,  5,  7,  9, 11])

In [82]:
a=a.reshape(2,3) #reshape
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [98]:
#ravel() --> flatterns your array
print(np.array(a.flat))
print(a.ravel())


[ 1  3  5  7  9 11]
[ 1  3  5  7  9 11]


## Function
1. min 
2. max
3. sum()
4. sqrt()
5. mean()
6. median()
7. std() #standard deviation

In [86]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [84]:
a.min()

1

In [85]:
a.max()

11

In [91]:
print(a.sum())
print(a.sum(axis=1)) # sum of row elements
print(a.sum(axis=0)) #sum of coloum elements

36
[ 9 27]
[ 8 12 16]


In [92]:
np.sqrt(a)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479]])

In [93]:
np.mean(a)

6.0

In [94]:
np.median(a)

6.0

In [95]:
np.std(a)

3.415650255319866

In [100]:
# Mathematical operations. +,-,*,/.%
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)

[12 14 16 18 20 22 24 26 28 30]
[-10 -10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171 200]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421 0.5       ]
[ 1  2  3  4  5  6  7  8  9 10]


 ## dot()--> Matrix mutiplication
 ## arr1 = m x n   
## arr2 = n x l   

In [102]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [103]:
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
#Transpose of an array
arr1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

 ## Applying user defined function:
    

In [105]:
l1 =list(range(1,20))
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [109]:
a = np.array(l1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [107]:
#/1/(1+1) --> x/(x+1)
result = [x/(x+1) for x in l1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [111]:
f= np.vectorize(lambda x: x/(x+1))#working with userdefined function on arry
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])