In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1


92
0.4469879749048451


In [8]:
#creating ndimensional array with random integers values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[ 9 23 50]
[[54 90 13 24]
 [81 90 19 47]
 [68 15 30 56]]
[[[42 99]
  [89 77]
  [31 41]
  [49 22]]

 [[74 31]
  [93 97]
  [90 22]
  [68 45]]

 [[39 49]
  [19 69]
  [15 27]
  [22  4]]]


In [10]:
#creating ndimensional array with random floating-point values
print(random.rand())
print(random.rand(3,4))
print(random.rand(3,4,2))

0.752462163383574
[[0.38372438 0.11055516 0.20421169 0.17279831]
 [0.05311579 0.97157317 0.2601974  0.1328309 ]
 [0.13933668 0.70831105 0.14734046 0.97675557]]
[[[0.286993   0.895695  ]
  [0.76791097 0.44620688]
  [0.75586541 0.33895968]
  [0.47055082 0.12703487]]

 [[0.25077976 0.49377652]
  [0.96664833 0.98219662]
  [0.69193463 0.76657365]
  [0.73981442 0.41935204]]

 [[0.57440892 0.12515654]
  [0.35776854 0.17538483]
  [0.87728907 0.36931424]
  [0.01637036 0.19180421]]]


In [14]:
a=random.randint(100,size=(3,2)).ravel()
a

array([ 0, 46, 55, 21, 58, 45])

In [15]:
#single element will be selected
random.choice(a)

55

In [17]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(4,4))

array([[3, 1, 1, 4],
       [3, 4, 1, 2],
       [4, 2, 4, 4],
       [1, 1, 3, 5]])

## Pandas:
1. data manipulation,analysis and cleaning
2. tabular, unlabelled data


## Creating a DataFrame
1. using 2 dictionaries
2. simple dictionary --> DataFrame

In [18]:
import pandas as pd
import numpy as np

In [24]:
dic1 ={'a':1,'b':2,'c':3,'d':4,'e':5}
dic2 ={'a':5,'b':6,'c':7,'d':8,'e':9}
data ={"First":dic1,"Second":dic2}
df=pd.DataFrame(data,dtype=np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [26]:
#simple dictionary --> DataFrame
d1 = {'name':["ram",'raj','rao'],'address':['hyd','adb','ap']}
df1 =pd.DataFrame(d1)
df1

name address
0  ram     hyd
1  raj     adb
2  rao      ap

In [29]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([12.23,23.34,45.3,45.50,67.4,67.78,34.45,23.34,67.4,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={'col1':s1,'col2':s2,"col3":s3}
df3=pd.DataFrame(data)
df3

col1   col2 col3
0     1  12.23    a
1     2  23.34    b
2     3  45.30    c
3     4  45.50    d
4     5  67.40    e
5     6  67.78    f
6     7  34.45    g
7     8  23.34    h
8     9  67.40    i
9    10  23.00    j

## 3 Selecting the data from the data frame
1. loc
2. iloc

In [30]:
df3['col2']

0    12.23
1    23.34
2    45.30
3    45.50
4    67.40
5    67.78
6    34.45
7    23.34
8    67.40
9    23.00
Name: col2, dtype: float64

In [32]:
df3[['col2','col3']]

col2 col3
0  12.23    a
1  23.34    b
2  45.30    c
3  45.50    d
4  67.40    e
5  67.78    f
6  34.45    g
7  23.34    h
8  67.40    i
9  23.00    j

In [37]:
#sinle column
df3.loc[:,'col1']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [40]:
#extracting multiple column values
df3.loc[0:5,["col1",'col2']]

col1   col2
0     1  12.23
1     2  23.34
2     3  45.30
3     4  45.50
4     5  67.40
5     6  67.78

In [41]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [42]:
df3.iloc[0:4,0:1]

col1
0     1
1     2
2     3
3     4

In [43]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     int64  
 1   col2    10 non-null     float64
 2   col3    10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [44]:
df3.shape

(10, 3)

In [46]:
df3.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [47]:
df3.index

RangeIndex(start=0, stop=10, step=1)

## Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [51]:
#first five rows are returned by default 
df3.head()

col1   col2 col3
0     1  12.23    a
1     2  23.34    b
2     3  45.30    c
3     4  45.50    d
4     5  67.40    e

In [50]:
df3.head(3)

col1   col2 col3
0     1  12.23    a
1     2  23.34    b
2     3  45.30    c

In [52]:
#by default we get last 5 rows
df3.tail()

col1   col2 col3
5     6  67.78    f
6     7  34.45    g
7     8  23.34    h
8     9  67.40    i
9    10  23.00    j

In [53]:
df3.tail(2)

col1  col2 col3
8     9  67.4    i
9    10  23.0    j

In [54]:
#we get randomly a row
df3.sample()

col1   col2 col3
5     6  67.78    f

In [55]:
df3.sample(2)

col1  col2 col3
8     9  67.4    i
4     5  67.4    e

In [56]:
df3.describe()

col1       col2
count  10.00000  10.000000
mean    5.50000  40.974000
std     3.02765  20.997852
min     1.00000  12.230000
25%     3.25000  23.340000
50%     5.50000  39.875000
75%     7.75000  61.925000
max    10.00000  67.780000

In [60]:
#renaming
df3=df3.rename(columns={"col1":"First","col2":"Second","col3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   45.30     c
3      4   45.50     d
4      5   67.40     e
5      6   67.78     f
6      7   34.45     g
7      8   23.34     h
8      9   67.40     i
9     10   23.00     j