# CSE-221710308039-VINAY

In [2]:
#1.Write a NumPy program to reverse an array (first element becomes last). 
import numpy as np
x=np.arange(12,38)
print(x)
print(x[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [12]:
#2.Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
o=np.ones((5,5))
o[1:4,1:4]=0
print(o)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#3.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.
arr1=np.array([0,10,20,40,60])
print("array1: ",arr1)
arr2=np.array([0,40])
print("array2: ",arr2)
result=np.in1d(arr1,arr2)
print(result)

array1:  [ 0 10 20 40 60]
array2:  [ 0 40]
[ True False False  True False]


In [17]:
#4.Write a NumPy program to find the set difference of two arrays. 
#The set difference will return the sorted, unique values in array1 that are not in array2.

arr3 = np.array([0, 10, 20, 40, 60, 80])
print("array1: ",arr3)
arr4 = [10, 30, 40, 50, 70]
print("array2: ",arr4)
print("Set difference between two arrays:",np.setdiff1d(arr3, arr4))

array1:  [ 0 10 20 40 60 80]
array2:  [10, 30, 40, 50, 70]
Set difference between two arrays: [ 0 20 60 80]


In [18]:
#5.Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's 
arr6= np.diagflat([4, 5, 6, 8])
print(arr6)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
